# -*- coding: utf-8 -*-
"""난생처음_실습.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g8M7k24oxhkTdim_sc9cYpUOazBMoNZA

# **3장. 파일 입출력**
"""

from google.colab import files

#파일 업로드 함수 호출하기
f = files.upload()

f = open('characters.csv' ,'r', encoding = 'utf-8')
#MAC os, linux -> utf-8

import csv

rdr = csv.reader(f)
print(rdr)

#반복문으로 한 행씩 출력하기
for line in rdr:
  print(line)

f = open('characters.csv' ,'r', encoding = 'utf-8')
rdr = csv.reader(f)

for line in rdr:
  print(line[1])

f.close()

import csv

f = open('write.csv', 'w', encoding='utf-8',newline='')

wr = csv.writer(f)

wr.writerow(['ID', '이름','상징색','취미', '특징'])
wr.writerow(['001', ' 뽀로로', ' 파랑색', ' 낚시', ' 펭귄'])
wr.writerow(['002', ' 에디', ' 주황색', ' 과학실험', ' 사막여우'])
wr.writerow(['003', ' 크롱', ' 초록색', ' 눈싸움', ' 공룡'])
wr.writerow(['004', ' 루피', ' 분홍색', ' 요리', ' 비버'])
wr.writerow(['005', ' 패티', ' 보라색', ' 운동', ' 펭귄'])

f.close()

f = open('write.csv', 'a', encoding = 'utf-8', newline='')
wr = csv.writer(f)

wr.writerow(['006', ' 포비', '흰색', '춤', ' 북극곰'])

f.close()

from google.colab import files
f = files.upload()

!pip install openpyxl
import openpyxl

wb = openpyxl.load_workbook('characters.xlsx')

print(wb)

print(wb.sheetnames)

sheet1 = wb['Sheet1']
print(sheet1['A1'].value)

#새 워크북 생성

wb = openpyxl.Workbook()

#새 워크시트 생성하기
wb.create_sheet('Sheet2')

#시트 이름 출력하기
print(wb.sheetnames)

sheet1 = wb['Sheet']
sheet2 = wb['Sheet2']

sheet1.title = '캐릭터 명단'
sheet2.title = '인기도 조사'

print(wb.sheetnames)

sheet2['B1'] = '인기도 조사결과'
print(sheet2['B1'].value)

copysheet = wb.copy_worksheet(sheet2)
print(wb.sheetnames)

copysheet.title = 'copy'

print(wb.sheetnames)
print(copysheet['B1'].value)

#워크시트 삭제하기
del wb['인기도 조사']
print(wb.sheetnames)

wb.save('complete.xlsx')

from google.colab import files

f = files.upload()

import openpyxl

wb = openpyxl.Workbook()
ws = wb.active

import csv

#csv 라이브러리의 reader()함수로 'data1.csv' 파일의 내용을 읽어 변수 reader에 담는다.
#for 반복문으로 변수 reader의 행을 하나씩 워크시트 ws에 추가한다.
with open('data1.csv', encoding = 'cp949') as f:
  reader = csv.reader(f)
  for row in reader:
    ws.append(row)

ws2 = wb.create_sheet('Sheet2') #워크북 wb에 워크시트 ws2를 생성한다.

with open('data2.csv', encoding = 'cp949') as f:
  reader = csv.reader(f)
  for row in reader:
    ws2.append(row)

ws3 = wb.create_sheet('Sheet3') #워크북 wb에 워크시트 ws3를 생성한다.

with open('data3.csv', encoding = 'cp949') as f:
  reader = csv.reader(f)
  for row in reader:
    ws3.append(row)

ws.title = '경기도 의정부시_의정부경전철 혼잡도'
ws2.title = '대전교통공사_열차 혼잡도 분석'
ws3.title ='서울특별시_지하철 혼잡도 정보'

wb.save('traffic.xlsx')





